import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera, PerspectiveCamera } from "@react-three/drei";

import { Canvas } from "@react-three/fiber";

export default function Scene({ ...props }) {
	return (
		<Canvas>
			<SceneContent {...props} />
		</Canvas>
	);
}

/*
  Auto-generated by Spline
*/

function SceneContent({ ...props }) {
	const { nodes, materials } = useSpline(
		"https://prod.spline.design/r0ZUySqcJPwMFSGy/scene.splinecode"
	);
	return (
		<>
			<color
				attach="background"
				args={["#494949"]}
			/>
			<group
				{...props}
				dispose={null}
			>
				<scene name="Scene">
					<mesh
						name="Rectangle"
						geometry={nodes.Rectangle.geometry}
						material={materials["Rectangle Material"]}
						castShadow
						receiveShadow
						position={[411.2, -390.77, 154.52]}
						rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
					/>
					<group
						name="clapper"
						position={[363.8, -249.66, 498.83]}
						rotation={[-3.01, 1.4, -3.12]}
						scale={[-0.36, 0.37, 0.37]}
					>
						<group
							name="Group"
							position={[1.07, 314.21, 24.19]}
							rotation={[0.3, 0.01, 0]}
						>
							<mesh
								name="Rectangle 2"
								geometry={nodes["Rectangle 2"].geometry}
								material={materials[""]}
								castShadow
								receiveShadow
								position={[2.98, 4.1, 5.2]}
								rotation={[2.86, -1.03, 2.9]}
								scale={[1, 1, 4.26]}
							/>
							<mesh
								name="Cube 2"
								geometry={nodes["Cube 2"].geometry}
								material={materials["Cube 2 Material"]}
								castShadow
								receiveShadow
								position={[-9.96, -1.61, -5.75]}
								rotation={[-0.27, 1.03, 0.24]}
								scale={1}
							/>
						</group>
						<group
							name="Group 2"
							position={[0, -57.54, 0.09]}
						>
							<mesh
								name="Rectangle 21"
								geometry={nodes["Rectangle 21"].geometry}
								material={materials["Rectangle 21 Material"]}
								castShadow
								receiveShadow
								position={[15.63, -39.54, 9.61]}
								rotation={[0, Math.PI / 3, 0]}
								scale={1}
							/>
							<mesh
								name="Rectangle 3"
								geometry={nodes["Rectangle 3"].geometry}
								material={materials["Rectangle 3 Material"]}
								castShadow
								receiveShadow
								position={[156.03, 58.04, -233.56]}
								rotation={[0, Math.PI / 3, 0]}
								scale={1}
							/>
							<mesh
								name="Rectangle1"
								geometry={nodes.Rectangle1.geometry}
								material={materials["Rectangle1 Material"]}
								castShadow
								receiveShadow
								position={[-27.16, 58.04, 83.73]}
								rotation={[0, Math.PI / 3, 0]}
								scale={1}
							/>
							<mesh
								name="Rectangle2"
								geometry={nodes.Rectangle2.geometry}
								material={materials[""]}
								castShadow
								receiveShadow
								position={[15.15, 183.81, 8.86]}
								rotation={[0.01, 1.05, 0]}
								scale={[1, 1, 4.26]}
							/>
							<mesh
								name="Cube"
								geometry={nodes.Cube.geometry}
								material={materials["Cube Material"]}
								castShadow
								receiveShadow
								position={[0, 0, 0]}
								rotation={[0, Math.PI / 3, 0]}
								scale={1}
							/>
						</group>
					</group>
					<group
						name="Studio light"
						position={[-66.88, -369.68, -1063.61]}
						rotation={[-2.58, -1.32, -2.42]}
						scale={31.62}
					>
						<group
							name="Group1"
							position={[26.31, 14.75, 13.31]}
							rotation={[0, 0.98, 0]}
							scale={2.14}
						>
							<pointLight
								name="Point Light"
								castShadow
								intensity={10}
								decay={10}
								distance={5385}
								shadow-mapSize-width={1024}
								shadow-mapSize-height={1024}
								shadow-camera-near={100}
								shadow-camera-far={100000}
								position={[0, 0, 0]}
								rotation={[0, 1.01, 0]}
								scale={[0.06, 0.01, 0.02]}
							/>
							<mesh
								name="Sphere"
								geometry={nodes.Sphere.geometry}
								material={materials["Sphere Material"]}
								castShadow
								receiveShadow
								rotation={[-Math.PI, 0, -Math.PI]}
								scale={0.01}
							/>
						</group>
						<mesh
							name="Studio_Light Light_head bulb Torus"
							geometry={nodes["Studio_Light Light_head bulb Torus"].geometry}
							material={nodes["Studio_Light Light_head bulb Torus"].material}
							castShadow
							receiveShadow
							position={[-29.34, -14.77, -14.87]}
							scale={2.14}
						/>
						<mesh
							name="Studio_Light Light_head Cube_10"
							geometry={nodes["Studio_Light Light_head Cube_10"].geometry}
							material={nodes["Studio_Light Light_head Cube_10"].material}
							castShadow
							receiveShadow
							position={[-29.34, -14.77, -14.87]}
							scale={2.14}
						/>
						<mesh
							name="Studio_Light Light_head Cube_9"
							geometry={nodes["Studio_Light Light_head Cube_9"].geometry}
							material={nodes["Studio_Light Light_head Cube_9"].material}
							castShadow
							receiveShadow
							position={[-29.34, -14.77, -14.87]}
							scale={2.14}
						/>
						<mesh
							name="Studio_Light Light_head Cube_8"
							geometry={nodes["Studio_Light Light_head Cube_8"].geometry}
							material={nodes["Studio_Light Light_head Cube_8"].material}
							castShadow
							receiveShadow
							position={[-29.34, -14.77, -14.87]}
							scale={2.14}
						/>
						<mesh
							name="Studio_Light Light_head Cube_7"
							geometry={nodes["Studio_Light Light_head Cube_7"].geometry}
							material={nodes["Studio_Light Light_head Cube_7"].material}
							castShadow
							receiveShadow
							position={[-29.34, -14.77, -14.87]}
							scale={2.14}
						/>
						<mesh
							name="Studio_Light Light_head Cube_6"
							geometry={nodes["Studio_Light Light_head Cube_6"].geometry}
							material={nodes["Studio_Light Light_head Cube_6"].material}
							castShadow
							receiveShadow
							position={[-29.34, -14.77, -14.87]}
							scale={2.14}
						/>
						<mesh
							name="Studio_Light Light_head Cube_5"
							geometry={nodes["Studio_Light Light_head Cube_5"].geometry}
							material={nodes["Studio_Light Light_head Cube_5"].material}
							castShadow
							receiveShadow
							position={[-29.34, -14.77, -14.87]}
							scale={2.14}
						/>
						<mesh
							name="Studio_Light Light_head Cube_4"
							geometry={nodes["Studio_Light Light_head Cube_4"].geometry}
							material={nodes["Studio_Light Light_head Cube_4"].material}
							castShadow
							receiveShadow
							position={[-29.34, -14.77, -14.87]}
							scale={2.14}
						/>
						<mesh
							name="Studio_Light Light_head Cube_2"
							geometry={nodes["Studio_Light Light_head Cube_2"].geometry}
							material={nodes["Studio_Light Light_head Cube_2"].material}
							castShadow
							receiveShadow
							position={[-29.34, -14.77, -14.87]}
							scale={2.14}
						/>
						<mesh
							name="Studio_Light Light_head Cube_3"
							geometry={nodes["Studio_Light Light_head Cube_3"].geometry}
							material={nodes["Studio_Light Light_head Cube_3"].material}
							castShadow
							receiveShadow
							position={[-29.34, -14.77, -14.87]}
							scale={2.14}
						/>
						<mesh
							name="Studio_Light Light_head HyperNURBS Cube_21"
							geometry={nodes["Studio_Light Light_head HyperNURBS Cube_21"].geometry}
							material={nodes["Studio_Light Light_head HyperNURBS Cube_21"].material}
							castShadow
							receiveShadow
							position={[-29.34, -14.77, -14.87]}
							scale={2.14}
						/>
						<mesh
							name="Studio_Light Light_Stand _"
							geometry={nodes["Studio_Light Light_Stand _"].geometry}
							material={nodes["Studio_Light Light_Stand _"].material}
							castShadow
							receiveShadow
						/>
						<mesh
							name="Studio_Light Light_Stand _1"
							geometry={nodes["Studio_Light Light_Stand _1"].geometry}
							material={nodes["Studio_Light Light_Stand _1"].material}
							castShadow
							receiveShadow
						/>
						<mesh
							name="Studio_Light Light_Stand _2"
							geometry={nodes["Studio_Light Light_Stand _2"].geometry}
							material={nodes["Studio_Light Light_Stand _2"].material}
							castShadow
							receiveShadow
						/>
						<mesh
							name="Studio_Light Light_Stand nub12"
							geometry={nodes["Studio_Light Light_Stand nub12"].geometry}
							material={nodes["Studio_Light Light_Stand nub12"].material}
							castShadow
							receiveShadow
						/>
						<mesh
							name="Studio_Light Light_Stand nub13"
							geometry={nodes["Studio_Light Light_Stand nub13"].geometry}
							material={nodes["Studio_Light Light_Stand nub13"].material}
							castShadow
							receiveShadow
						/>
						<mesh
							name="Studio_Light Light_Stand nub1"
							geometry={nodes["Studio_Light Light_Stand nub1"].geometry}
							material={nodes["Studio_Light Light_Stand nub1"].material}
							castShadow
							receiveShadow
						/>
						<mesh
							name="Studio_Light Light_Stand nub11"
							geometry={nodes["Studio_Light Light_Stand nub11"].geometry}
							material={nodes["Studio_Light Light_Stand nub11"].material}
							castShadow
							receiveShadow
						/>
						<mesh
							name="Studio_Light Light_Stand Sphere"
							geometry={nodes["Studio_Light Light_Stand Sphere"].geometry}
							material={nodes["Studio_Light Light_Stand Sphere"].material}
							castShadow
							receiveShadow
							position={[-14.61, -7.17, -8.27]}
							scale={1.58}
						/>
						<mesh
							name="Studio_Light Light_Stand Cube_1"
							geometry={nodes["Studio_Light Light_Stand Cube_1"].geometry}
							material={nodes["Studio_Light Light_Stand Cube_1"].material}
							castShadow
							receiveShadow
							position={[-14.61, -7.17, -8.27]}
							scale={1.58}
						/>
						<mesh
							name="Studio_Light Light_Stand main_pole"
							geometry={nodes["Studio_Light Light_Stand main_pole"].geometry}
							material={nodes["Studio_Light Light_Stand main_pole"].material}
							castShadow
							receiveShadow
						/>
						<mesh
							name="Studio_Light Light_Stand Cube"
							geometry={nodes["Studio_Light Light_Stand Cube"].geometry}
							material={nodes["Studio_Light Light_Stand Cube"].material}
							castShadow
							receiveShadow
						/>
						<mesh
							name="Studio_Light Light_Stand Cylinder_3"
							geometry={nodes["Studio_Light Light_Stand Cylinder_3"].geometry}
							material={nodes["Studio_Light Light_Stand Cylinder_3"].material}
							castShadow
							receiveShadow
						/>
						<mesh
							name="Studio_Light Light_Stand Cylinder_2"
							geometry={nodes["Studio_Light Light_Stand Cylinder_2"].geometry}
							material={nodes["Studio_Light Light_Stand Cylinder_2"].material}
							castShadow
							receiveShadow
						/>
						<mesh
							name="Studio_Light Light_Stand Cylinder"
							geometry={nodes["Studio_Light Light_Stand Cylinder"].geometry}
							material={nodes["Studio_Light Light_Stand Cylinder"].material}
							castShadow
							receiveShadow
						/>
						<mesh
							name="Studio_Light Light_Stand Cylinder_1"
							geometry={nodes["Studio_Light Light_Stand Cylinder_1"].geometry}
							material={nodes["Studio_Light Light_Stand Cylinder_1"].material}
							castShadow
							receiveShadow
						/>
					</group>
					<group
						name="iPhone 13 Pro"
						position={[4, -4.5, 3]}
						rotation={[-0.29, -0.22, -0.18]}
						scale={1}
					>
						<group
							name="Notch Details"
							position={[-11.5, 252.79, 15.88]}
							scale={1}
						>
							<mesh
								name="Ellipse 2"
								geometry={nodes["Ellipse 2"].geometry}
								material={materials["Ellipse 2 Material"]}
								castShadow
								receiveShadow
								position={[-24.5, -4.79, 0.07]}
							/>
							<mesh
								name="Ellipse"
								geometry={nodes.Ellipse.geometry}
								material={materials["Ellipse Material"]}
								castShadow
								receiveShadow
								position={[-24.5, -4.79, -0.07]}
							/>
							<mesh
								name="Rectangle 5"
								geometry={nodes["Rectangle 5"].geometry}
								material={materials["Rectangle 5 Material"]}
								castShadow
								receiveShadow
								position={[11.5, 8.79, -0.01]}
							/>
						</group>
						<group
							name="Connectors"
							position={[0, 0, 0]}
							scale={1}
						>
							<mesh
								name="Rectangle 4"
								geometry={nodes["Rectangle 4"].geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[79.53, 137.8, 0]}
								rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
								scale={1}
							/>
							<mesh
								name="Rectangle 31"
								geometry={nodes["Rectangle 31"].geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[-62.45, -137.8, 0]}
								rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
								scale={1}
							/>
							<mesh
								name="Rectangle 22"
								geometry={nodes["Rectangle 22"].geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[0, -214.5, 0]}
								rotation={[-Math.PI / 2, 0, 0]}
							/>
							<mesh
								name="Rectangle3"
								geometry={nodes.Rectangle3.geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[0, 211.23, 0]}
								rotation={[-Math.PI / 2, 0, 0]}
							/>
						</group>
						<group
							name="Bottom Details"
							position={[7.82, -269.08, 0]}
							scale={1}
						>
							<mesh
								name="Ellipse 6"
								geometry={nodes["Ellipse 6"].geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[-35.18, 0.08, 0]}
								rotation={[Math.PI / 2, 0, 0]}
							/>
							<mesh
								name="Ellipse 5"
								geometry={nodes["Ellipse 5"].geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[59.18, 0.08, 0]}
								rotation={[Math.PI / 2, 0, 0]}
							/>
							<mesh
								name="Ellipse 61"
								geometry={nodes["Ellipse 61"].geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[-51.18, 0.08, 0]}
								rotation={[Math.PI / 2, 0, 0]}
							/>
							<mesh
								name="Ellipse 4"
								geometry={nodes["Ellipse 4"].geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[51.18, 0.08, 0]}
								rotation={[Math.PI / 2, 0, 0]}
							/>
							<mesh
								name="Ellipse 3"
								geometry={nodes["Ellipse 3"].geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[43.18, 0.08, 0]}
								rotation={[Math.PI / 2, 0, 0]}
							/>
							<mesh
								name="Ellipse 62"
								geometry={nodes["Ellipse 62"].geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[-59.18, 0.08, 0]}
								rotation={[Math.PI / 2, 0, 0]}
							/>
							<mesh
								name="Ellipse 21"
								geometry={nodes["Ellipse 21"].geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[35.18, 0.08, 0]}
								rotation={[Math.PI / 2, 0, 0]}
							/>
							<mesh
								name="Ellipse1"
								geometry={nodes.Ellipse1.geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[20.18, 0.08, 0]}
								rotation={[Math.PI / 2, 0, 0]}
							/>
							<mesh
								name="Rectangle 23"
								geometry={nodes["Rectangle 23"].geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[-7.82, -0.08, 0]}
								rotation={[Math.PI / 2, 0, 0]}
							/>
							<mesh
								name="Rectangle4"
								geometry={nodes.Rectangle4.geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[-7.82, 0.08, 0]}
								rotation={[Math.PI / 2, 0, 0]}
							/>
						</group>
						<group
							name="Logo"
							position={[26.33, 59.32, -14.8]}
							rotation={[-Math.PI, 0, -Math.PI]}
							scale={[0.07, 0.07, 0]}
						>
							<mesh
								name="Untitled"
								geometry={nodes.Untitled.geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[181, -238, 0]}
							/>
							<mesh
								name="Untitled1"
								geometry={nodes.Untitled1.geometry}
								material={materials["Pink Items"]}
								castShadow
								receiveShadow
								position={[423, -1, 0.01]}
							/>
						</group>
						<group
							name="Camera"
							position={[63.33, 203.33, -15.06]}
							scale={1}
						>
							<mesh
								name="Ellipse 22"
								geometry={nodes["Ellipse 22"].geometry}
								material={materials["Camera Lens 2 Inner"]}
								castShadow
								receiveShadow
								position={[-39.92, 31.41, -3.94]}
								rotation={[-Math.PI, 0, -Math.PI]}
							/>
							<mesh
								name="Ellipse2"
								geometry={nodes.Ellipse2.geometry}
								material={materials["Camera Lens 2 Inner"]}
								castShadow
								receiveShadow
								position={[-31.83, 31.41, -3.94]}
								rotation={[-Math.PI, 0, -Math.PI]}
							/>
							<mesh
								name="Cylinder copy"
								geometry={nodes["Cylinder copy"].geometry}
								material={materials["Cylinder copy Material"]}
								castShadow
								receiveShadow
								position={[33.93, -43.33, 1.5]}
								rotation={[-Math.PI / 2, 0, 0]}
							/>
							<group
								name="Light"
								position={[-34.62, 30.45, -1.91]}
								rotation={[0, 0, 0]}
								scale={[1, 1, 0.9]}
							>
								<mesh
									name="Ellipse 23"
									geometry={nodes["Ellipse 23"].geometry}
									material={materials["Ellipse 23 Material"]}
									castShadow
									receiveShadow
									position={[0, 0, 0.66]}
									rotation={[-Math.PI, 0, Math.PI]}
									scale={[0.91, 0.91, 1]}
								/>
								<mesh
									name="Ellipse3"
									geometry={nodes.Ellipse3.geometry}
									material={materials["Camera Lens 2"]}
									castShadow
									receiveShadow
									position={[0, 0, 0.34]}
									rotation={[-Math.PI, 0, Math.PI]}
									scale={[0.91, 0.91, 1]}
								/>
							</group>
							<group
								name="Cam2"
								position={[-22.34, -21.24, -2.15]}
								scale={1}
							>
								<mesh
									name="Ellipse 7"
									geometry={nodes["Ellipse 7"].geometry}
									material={materials["Pink Items"]}
									castShadow
									receiveShadow
									position={[0, 0, 0.93]}
									rotation={[-Math.PI, 0, Math.PI]}
								/>
								<mesh
									name="Ellipse 63"
									geometry={nodes["Ellipse 63"].geometry}
									material={materials["Ellipse 63 Material"]}
									castShadow
									receiveShadow
									position={[0, 0, 0.5]}
									rotation={[-Math.PI, 0, Math.PI]}
								/>
								<mesh
									name="Ellipse 51"
									geometry={nodes["Ellipse 51"].geometry}
									material={materials["Ellipse 51 Material"]}
									castShadow
									receiveShadow
									position={[-0.17, -0.12, 1.1]}
									rotation={[-Math.PI, 0, Math.PI]}
								/>
								<mesh
									name="Ellipse 41"
									geometry={nodes["Ellipse 41"].geometry}
									material={materials["Ellipse 41 Material"]}
									castShadow
									receiveShadow
									position={[-0.5, -0.19, 1.6]}
									rotation={[-Math.PI, 0, Math.PI]}
								/>
								<mesh
									name="Ellipse 9"
									geometry={nodes["Ellipse 9"].geometry}
									material={materials["Ellipse 9 Material"]}
									castShadow
									receiveShadow
									position={[-3.5, 2, -2.32]}
									rotation={[-Math.PI, 0, Math.PI]}
									scale={0.5}
								/>
								<mesh
									name="Ellipse 8"
									geometry={nodes["Ellipse 8"].geometry}
									material={materials["Ellipse 8 Material"]}
									castShadow
									receiveShadow
									position={[1.5, -2, -2.32]}
									rotation={[-Math.PI, 0, Math.PI]}
								/>
								<mesh
									name="Ellipse 31"
									geometry={nodes["Ellipse 31"].geometry}
									material={materials["Ellipse 31 Material"]}
									castShadow
									receiveShadow
									position={[-0.5, 0, 2.5]}
									rotation={[-Math.PI, 0, Math.PI]}
								/>
							</group>
							<group
								name="Cam1"
								position={[23.72, 21.5, -2.15]}
								scale={1}
							>
								<mesh
									name="Ellipse 71"
									geometry={nodes["Ellipse 71"].geometry}
									material={materials["Pink Items"]}
									castShadow
									receiveShadow
									position={[0, 0, 0.93]}
									rotation={[-Math.PI, 0, Math.PI]}
								/>
								<mesh
									name="Ellipse 64"
									geometry={nodes["Ellipse 64"].geometry}
									material={materials["Ellipse 64 Material"]}
									castShadow
									receiveShadow
									position={[0, 0, 0.5]}
									rotation={[-Math.PI, 0, Math.PI]}
								/>
								<mesh
									name="Ellipse 52"
									geometry={nodes["Ellipse 52"].geometry}
									material={materials["Ellipse 52 Material"]}
									castShadow
									receiveShadow
									position={[-0.17, -0.12, 1.1]}
									rotation={[-Math.PI, 0, Math.PI]}
								/>
								<mesh
									name="Ellipse 42"
									geometry={nodes["Ellipse 42"].geometry}
									material={materials["Ellipse 42 Material"]}
									castShadow
									receiveShadow
									position={[-0.5, -0.19, 1.6]}
									rotation={[-Math.PI, 0, Math.PI]}
								/>
								<mesh
									name="Ellipse 91"
									geometry={nodes["Ellipse 91"].geometry}
									material={materials["Ellipse 91 Material"]}
									castShadow
									receiveShadow
									position={[-3.5, 2, -2.32]}
									rotation={[-Math.PI, 0, Math.PI]}
									scale={0.5}
								/>
								<mesh
									name="Ellipse 81"
									geometry={nodes["Ellipse 81"].geometry}
									material={materials["Ellipse 81 Material"]}
									castShadow
									receiveShadow
									position={[1.5, -2, -2.32]}
									rotation={[-Math.PI, 0, Math.PI]}
								/>
								<mesh
									name="Ellipse 32"
									geometry={nodes["Ellipse 32"].geometry}
									material={materials["Ellipse 32 Material"]}
									castShadow
									receiveShadow
									position={[-0.5, 0, 2.5]}
									rotation={[-Math.PI, 0, Math.PI]}
								/>
							</group>
							<group
								name="Empty Object"
								position={[0, 0, 2.15]}
								rotation={[0, 0, 0]}
								scale={1}
							>
								<mesh
									name="Rectangle 24"
									geometry={nodes["Rectangle 24"].geometry}
									material={materials.Metal}
									castShadow
									receiveShadow
									position={[0, 0, 2.97]}
									rotation={[-Math.PI, 0, Math.PI]}
									scale={[0.94, 0.87, 0.94]}
								/>
								<mesh
									name="Rectangle5"
									geometry={nodes.Rectangle5.geometry}
									material={materials["Pink Items"]}
									castShadow
									receiveShadow
									position={[0, 0, 3.6]}
									rotation={[-Math.PI, 0, Math.PI]}
									scale={[0.94, 0.87, 0.94]}
								/>
							</group>
						</group>
						<group
							name="Body"
							position={[10.63, 18.95, 0.83]}
							scale={[1.02, 1.02, 1.04]}
						>
							<mesh
								name="Screen"
								geometry={nodes.Screen.geometry}
								material={materials["Screen Material"]}
								castShadow
								receiveShadow
								position={[-10.55, -18.77, 14.69]}
								scale={[0.98, 0.98, 0.96]}
							/>
							<mesh
								name="Screen Border"
								geometry={nodes["Screen Border"].geometry}
								material={materials["Black Border"]}
								castShadow
								receiveShadow
								position={[-10.45, -18.61, 14.39]}
								rotation={[-Math.PI, 0, Math.PI]}
								scale={[1.08, 1.08, 1.06]}
							/>
							<mesh
								name="Back Side"
								geometry={nodes["Back Side"].geometry}
								material={materials.Metal}
								castShadow
								receiveShadow
								position={[-10.04, -18.07, -9.56]}
								rotation={[-Math.PI, 0, Math.PI]}
								scale={[1.08, 1.08, 1.06]}
							/>
							<group
								name="Left Buttons"
								position={[-139.66, 74.64, 0.26]}
								scale={[0.98, 0.98, 0.96]}
							>
								<mesh
									name="Ellipse4"
									geometry={nodes.Ellipse4.geometry}
									material={materials["Pink Items"]}
									castShadow
									receiveShadow
									position={[-0.02, -262.95, -0.09]}
									rotation={[0, -Math.PI / 2, 0]}
									scale={1}
								/>
								<mesh
									name="Rectangle 9"
									geometry={nodes["Rectangle 9"].geometry}
									material={materials["Pink Items"]}
									castShadow
									receiveShadow
									position={[0.77, 56.26, -0.26]}
									rotation={[0, -Math.PI / 2, 0]}
									scale={[1.04, 1.02, 1.02]}
								/>
								<mesh
									name="Rectangle 8"
									geometry={nodes["Rectangle 8"].geometry}
									material={materials["Pink Items"]}
									castShadow
									receiveShadow
									position={[-1.51, 56.26, 2.07]}
									rotation={[0, Math.PI / 2, 0]}
									scale={[1.04, 1.02, 1.02]}
								/>
								<mesh
									name="Rectangle 7"
									geometry={nodes["Rectangle 7"].geometry}
									material={materials["Pink Items"]}
									castShadow
									receiveShadow
									position={[-1.51, 5.86, 0]}
									rotation={[0, Math.PI / 2, 0]}
									scale={[1.04, 1.02, 1.02]}
								/>
								<mesh
									name="Rectangle 11"
									geometry={nodes["Rectangle 11"].geometry}
									material={materials.Metal}
									castShadow
									receiveShadow
									position={[0.24, -241.12, 0]}
									rotation={[0, -Math.PI / 2, 0]}
									scale={[1.04, 1.02, 1.02]}
								/>
								<mesh
									name="Rectangle 10"
									geometry={nodes["Rectangle 10"].geometry}
									material={materials["Pink Items"]}
									castShadow
									receiveShadow
									position={[0.54, -241.12, 0]}
									rotation={[0, -Math.PI / 2, 0]}
									scale={[1.04, 1.02, 1.02]}
								/>
								<mesh
									name="Rectangle 51"
									geometry={nodes["Rectangle 51"].geometry}
									material={materials["Pink Items"]}
									castShadow
									receiveShadow
									position={[-1.51, -42, 0]}
									rotation={[0, Math.PI / 2, 0]}
									scale={[1.04, 1.02, 1.02]}
								/>
							</group>
							<group
								name="Right Buttons"
								position={[118.57, -3.06, 0.26]}
								scale={[0.98, 0.98, 0.96]}
							>
								<mesh
									name="Button"
									geometry={nodes.Button.geometry}
									material={materials["Pink Items"]}
									castShadow
									receiveShadow
									position={[-0.25, -60.23, 0]}
									rotation={[0, Math.PI / 2, 0]}
									scale={[1.04, 1.02, 1.02]}
								/>
								<mesh
									name="Button1"
									geometry={nodes.Button1.geometry}
									material={materials["Pink Items"]}
									castShadow
									receiveShadow
									position={[-1.53, 60.23, 0]}
									rotation={[0, Math.PI / 2, 0]}
									scale={[1.04, 1.02, 1.02]}
								/>
							</group>
							<mesh
								name="Metal Border"
								geometry={nodes["Metal Border"].geometry}
								material={materials.Metal}
								castShadow
								receiveShadow
								position={[-10.45, -18.61, 13.04]}
								rotation={[-Math.PI, 0, Math.PI]}
								scale={[1.08, 1.08, 1.06]}
							/>
						</group>
					</group>
					<PerspectiveCamera
						name="Default Camera"
						makeDefault={true}
						far={49982}
						near={167}
						fov={31.4}
						position={[410.75, -151.61, 2593.79]}
						rotation={[-0.03, 0.17, 0.01]}
						scale={1}
					/>
					<OrthographicCamera
						name="1"
						makeDefault={false}
						far={10000}
						near={-50000}
					/>
				</scene>
			</group>
		</>
	);
}
